repos:
-   repo: https://github.com/ambv/black
    rev: '19.3b0'
    hooks:
    - id: black
      args: [--line-length=79]
# -   repo: https://github.com/pre-commit/mirrors-isort
#     rev: 'v4.3.20'
#     hooks:
#     -   id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: debug-statements
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.701'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args:
        - --follow-imports=error
-   repo: git@git.hypers.com:server-python/pre-commit-hooks.git
    rev: 9e5635
    hooks:
    - id: check
