stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: xiangcai
      registry: reg.xiangcaihua.com
- name: deploy
  steps:
  - applyAppConfig:
      catalogTemplate: xiangcai
      version: latest
      name: xiangcai-backend
      targetNamespace: default
timeout: 60
notification: {}
