stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: xiangcai/backend:latest
      pushRemote: true
      registry: reg.xiangcaihua.com
timeout: 60
notification: {}
