stages:
- name: build
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: |-
        cat >> config/.env << EOF
        DATABASE_URL='mysql://root:zhan@1996@106.15.186.207:31866/xiangcai?local_infile=1'
        EOF
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: xiangcai/backend:latest
      pushRemote: true
      registry: reg.xiangcaihua.com
- name: deploy
  steps:
  - applyAppConfig:
      catalogTemplate: xiangcai
      version: latest
      name: xiangcai
      targetNamespace: default
timeout: 60
notification: {}
