# Generated by Django 2.2.5 on 2019-11-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0004_auto_20191002_1147")]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="create_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="modify_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
