# Generated by Django 2.2.5 on 2019-11-26 01:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("blog", "0006_comment")]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=ckeditor.fields.RichTextField(),
        )
    ]
