# Generated by Django 2.2.5 on 2019-11-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0007_auto_20191126_0930")]

    operations = [
        migrations.AlterField(
            model_name="comment", name="body", field=models.TextField()
        )
    ]
