# Generated by Django 2.2.5 on 2019-11-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("blog", "0008_auto_20191126_1004")]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="body", new_name="content"
        )
    ]
