# Generated by Django 2.2.5 on 2020-01-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0009_auto_20191126_2131")]

    operations = [
        migrations.AddField(
            model_name="article",
            name="body_html",
            field=models.TextField(null=True),
        )
    ]
