# Generated by Django 2.2.5 on 2020-03-19 11:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0011_auto_20200204_2331"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="article", unique_together={("owner", "title")}
        )
    ]
