# Generated by Django 3.0.5 on 2020-04-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0013_auto_20200319_2019")]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="类别"
            ),
        )
    ]
